# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[amano-kenji]
location = /var/db/repos/amano-kenji
sync-type = git
sync-uri = https://github.com/gentoo-mirror/amano-kenji.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/steam-overlay.git

[4nykey]
location = /var/db/repos/4nykey
sync-type = git
sync-uri = https://github.com/gentoo-mirror/4nykey.git

[librewolf]
location = /var/db/repos/librewolf
sync-type = git
sync-uri = https://codeberg.org/librewolf/gentoo.git
